### PR TITLE
[MAZ-292] Add badge modal on homescreen

### PR DESCRIPTION
**Pull request by kriszzy01**

### CODE REVIEW

**Review by Dhaiwat10 — APPROVED** [review]
@kriszzy01 LGTM! Pls get this approved by Sebastian and we can merge! :)

**Comment by Dhaiwat10** [comment]
@kriszzy01 when I click anywhere _inside_ the badge modal, it is disappearing. Should this be happening?

**Comment by kriszzy01** [comment]
> @kriszzy01 when I click anywhere _inside_ the badge modal, it is disappearing. Should this be happening?

Fixed!

**Comment by kriszzy01** [comment]
> @kriszzy01 LGTM! Pls get this approved by Sebastian and we can merge! :)

Currently working on the audits for homescreen. Will send that over so Sebastian and I can review at once

**Pull request merged**
